name: leaseproof
description: Landlord inspection app for California compliance
version: 1.0.0+1
environment:
  sdk: ">=2.19.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  signature: ^5.5.0
  path_provider: ^2.1.5
  sqflite: ^2.4.2
  permission_handler: ^10.4.5
  image_picker: ^0.8.9
  location: ^4.4.0
  pdf: ^3.11.3
  printing: ^5.14.2
  google_sign_in: ^5.4.4
  googleapis: ^9.2.0
  googleapis_auth: ^1.4.1

dev_dependencies:
  flutter_test:
    sdk: flutter
