name: leaseproof
description: Landlord inspection app for California compliance
version: 1.0.0+1
environment:
  sdk: ">=2.19.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  signature: ^6.3.0
  path_provider: ^2.0.14
  sqflite: ^2.5.6
  permission_handler: ^13.2.0
  image_picker: ^1.1.2
  location: ^8.1.1
  pdf: ^3.11.3
  printing: ^5.14.2
  google_sign_in: ^7.0.3
  googleapis: ^14.0.0
  googleapis_auth: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
