name: leaseproof
description: A simple LeaseProof landlord inspection app
publish_to: 'none'
version: 0.1.0+1
environment:
  sdk: '>=2.18.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  sqflite: ^2.2.0
  path_provider: ^2.0.11
  path: ^1.8.3
  image_picker: ^0.8.7+4
  permission_handler: ^10.2.0
  location: ^4.4.0
  google_sign_in: ^5.4.2
  googleapis: ^9.0.0
  googleapis_auth: ^1.2.0
  pdf: ^3.10.1
  printing: ^5.10.1
  signature: ^5.5.0
  intl: ^0.18.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/sample_logo.png
